# Generated by Django 5.2.17 on 2026-09-13 19:55

import apps.extensions.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, max_length=16)),
                ('type', models.CharField(choices=[('dect', 'DECT handset'), ('sip', 'SIP endpoint'), ('gsm', 'GSM (local cell network)'), ('webrtc', 'WebRTC browser softphone'), ('analog', 'Analog via ATA'), ('group', 'Call group / hunt group'), ('announcement', 'Announcement'), ('ivr', 'IVR menu'), ('conference', 'Conference room'), ('voicemail', 'Voicemail box'), ('app', 'Application / service'), ('federation', 'Federation trunk (DIAL-VPN)'), ('breakout', 'PSTN breakout')], default='dect', max_length=20)),
                ('state', models.CharField(choices=[('requested', 'Requested - awaiting approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('deleted', 'Deleted')], db_index=True, default='requested', max_length=20)),
                ('display_name', models.CharField(blank=True, help_text='Caller-ID name.', max_length=60)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('location_hint', models.CharField(blank=True, help_text="e.g. 'Hackcenter, table 12'", max_length=120)),
                ('in_phonebook', models.BooleanField(default=True, verbose_name='Public phonebook entry')),
                ('language', models.CharField(blank=True, max_length=8)),
                ('ring_strategy', models.CharField(choices=[('parallel', 'Ring all devices at once'), ('serial', 'Ring devices one after another')], default='parallel', max_length=10)),
                ('ring_timeout', models.PositiveSmallIntegerField(default=30)),
                ('forward_busy', models.CharField(blank=True, max_length=16)),
                ('forward_noanswer', models.CharField(blank=True, max_length=16)),
                ('forward_unconditional', models.CharField(blank=True, max_length=16)),
                ('allow_callback', models.BooleanField(default=True, help_text='Allow CCBS/CCNR on this extension.')),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='0 = normal. Higher values can preempt (emergency/orga).')),
                ('is_temporary', models.BooleanField(default=False, help_text='Guest extension; expires automatically.')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('claim_token', models.CharField(blank=True, db_index=True, help_text='QR/deeplink token to claim a guest extension.', max_length=64)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('request_note', models.TextField(blank=True)),
                ('moderation_note', models.TextField(blank=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('provision_error', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='events.event')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extensions', to=settings.AUTH_USER_MODEL)),
                ('ported_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ported_to', to='extensions.extension')),
            ],
            options={
                'ordering': ['number'],
                'permissions': [('moderate_extension', 'Can approve/reject extensions')],
            },
        ),
        migrations.CreateModel(
            name='ExtensionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=16)),
                ('type', models.CharField(choices=[('dect', 'DECT handset'), ('sip', 'SIP endpoint'), ('gsm', 'GSM (local cell network)'), ('webrtc', 'WebRTC browser softphone'), ('analog', 'Analog via ATA'), ('group', 'Call group / hunt group'), ('announcement', 'Announcement'), ('ivr', 'IVR menu'), ('conference', 'Conference room'), ('voicemail', 'Voicemail box'), ('app', 'Application / service'), ('federation', 'Federation trunk (DIAL-VPN)'), ('breakout', 'PSTN breakout')], default='dect', max_length=20)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtensionTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=apps.extensions.models._new_token, max_length=64, unique=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='extensions.extension')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='extension',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['requested', 'active', 'suspended'])), fields=('event', 'number'), name='unique_live_number_per_event'),
        ),
        migrations.AlterUniqueTogether(
            name='extensionrequest',
            unique_together={('event', 'number', 'user')},
        ),
    ]
