# Generated by Django 5.2.17 on 2026-09-14 02:46

import apps.extensions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='call_waiting',
            field=models.BooleanField(default=True, help_text='Off: a second incoming call gets a busy signal instead of knocking.'),
        ),
        migrations.AddField(
            model_name='extension',
            name='dect_encryption',
            field=models.BooleanField(default=False, help_text='Encrypt the DECT air interface for handsets on this extension.'),
        ),
        migrations.AddField(
            model_name='extension',
            name='display_mode',
            field=models.CharField(choices=[('number_name', 'Number and name ("4242 Alice")'), ('name', 'Name only'), ('number', 'Number only')], default='number_name', help_text='What the called party sees as your caller ID.', max_length=12),
        ),
        migrations.AddField(
            model_name='extension',
            name='forward_delay',
            field=models.PositiveSmallIntegerField(default=10, help_text="Seconds to ring your own devices before forwarding (mode 'delayed')."),
        ),
        migrations.AddField(
            model_name='extension',
            name='forward_mode',
            field=models.CharField(choices=[('off', 'No forwarding'), ('always', 'Always (do not ring my devices)'), ('busy', 'When busy'), ('noanswer', 'When unanswered'), ('delayed', 'Delayed (ring my devices first, then forward)')], default='off', max_length=10),
        ),
        migrations.AddField(
            model_name='extension',
            name='forward_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_from', to='extensions.extension'),
        ),
        migrations.AddField(
            model_name='extension',
            name='ringback_tone',
            field=models.FileField(blank=True, null=True, upload_to='ringback/'),
        ),
        migrations.AddField(
            model_name='extension',
            name='ringback_tone_error',
            field=models.CharField(blank=True, editable=False, max_length=300),
        ),
        migrations.AddField(
            model_name='extension',
            name='ringback_tone_processed',
            field=models.FileField(blank=True, editable=False, null=True, upload_to=apps.extensions.models.ringback_processed_path),
        ),
        migrations.AddField(
            model_name='extension',
            name='ringback_tone_status',
            field=models.CharField(choices=[('none', 'No custom tone'), ('pending', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='none', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='extension',
            name='language',
            field=models.CharField(blank=True, choices=[('', 'Event default'), ('en', 'English'), ('de', 'Deutsch')], help_text='Language of voicemail and system announcements played to callers of this extension.', max_length=8),
        ),
    ]
