# Generated by Django 5.2.17 on 2026-09-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0002_ringback_forwarding_toggles'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='dect_claim_code',
            field=models.CharField(blank=True, db_index=True, help_text="Digits the owner dials (after the plan's DECT claim number) from any subscribed handset to bind that handset to this extension.", max_length=8),
        ),
    ]
