# Generated by Django 5.2.17 on 2026-09-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0003_dect_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='announcement_record_code',
            field=models.CharField(blank=True, db_index=True, help_text="Digits the owner dials (after the plan's announcement recording number) to record this announcement by phone.", max_length=8),
        ),
    ]
