# Generated by Django 5.2.17 on 2026-09-13 19:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('registration', 'Registration open'), ('live', 'Live'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('is_public', models.BooleanField(default=True, help_text='Listed publicly and joinable by any user.')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('timezone', models.CharField(default='Europe/Berlin', max_length=64)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='events/logos/')),
                ('primary_color', models.CharField(default='#3b82f6', max_length=7)),
                ('accent_color', models.CharField(default='#22d3ee', max_length=7)),
                ('announcement', models.TextField(blank=True, help_text='Shown on the event dashboard.')),
                ('sip_domain', models.CharField(blank=True, help_text='SIP realm, e.g. event.dial.local', max_length=120)),
                ('dial_prefix', models.CharField(blank=True, help_text='Prefix used by federated peers to reach this event (DIAL-VPN).', max_length=8)),
                ('default_language', models.CharField(default='en', max_length=8)),
                ('max_extensions_per_user', models.PositiveIntegerField(default=3)),
                ('allow_guest_extensions', models.BooleanField(default=False)),
                ('allow_breakout', models.BooleanField(default=False)),
                ('cdr_aggregate_only', models.BooleanField(default=False, help_text='Privacy: only keep aggregate statistics, no per-call records.')),
                ('cdr_retention_days', models.PositiveIntegerField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('cloned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='events.event')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('join_code', models.CharField(blank=True, help_text='Optional code users can enter to self-join this group.', max_length=32)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='events.event')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('event', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField()),
                ('secret', models.CharField(blank=True, help_text='HMAC-SHA256 signing secret.', max_length=128)),
                ('event_types', models.JSONField(default=list, help_text='List of event types; empty = all.')),
                ('is_active', models.BooleanField(default=True)),
                ('last_status', models.CharField(blank=True, max_length=40)),
                ('last_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='events.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('helpdesk', 'Helpdesk'), ('orga', 'Orga / Moderator'), ('admin', 'Event admin')], default='user', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, related_name='members', to='events.usergroup')),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
    ]
