# Generated by Django 5.2.17 on 2026-09-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gsm_trunk',
            field=models.CharField(blank=True, default='gsm-gateway', help_text='PJSIP endpoint name of the GSM gateway trunk.', max_length=60),
        ),
        migrations.AddField(
            model_name='event',
            name='has_gsm',
            field=models.BooleanField(default=False, help_text="An on-site GSM network (e.g. Osmocom/OpenBSC) is connected to this event's PBX."),
        ),
    ]
