# Generated by Django 5.2.17 on 2026-09-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_gsm'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='archives_at',
            field=models.DateTimeField(blank=True, help_text='Automatically archive the event at this time.', null=True, verbose_name='archives at'),
        ),
        migrations.AddField(
            model_name='event',
            name='goes_live_at',
            field=models.DateTimeField(blank=True, help_text='Automatically switch the event to live at this time.', null=True, verbose_name='goes live at'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_opens_at',
            field=models.DateTimeField(blank=True, help_text='Automatically open registration at this time.', null=True, verbose_name='registration opens at'),
        ),
    ]
