# Generated by Django 5.2.17 on 2026-09-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='default_language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'Deutsch')], default='en', help_text='Asterisk sound pack for voicemail prompts and system announcements; extensions may override it. The web interface itself is English only.', max_length=8, verbose_name='Announcement language'),
        ),
    ]
