# Generated by Django 5.2.17 on 2026-09-13 21:27

import apps.callback.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('extensions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ccbs', 'Completion of calls to busy subscriber'), ('ccnr', 'Completion of calls on no reply')], default='ccbs', max_length=4)),
                ('requester_number', models.CharField(max_length=16)),
                ('target_number', models.CharField(db_index=True, max_length=16)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('dialing', 'Dialing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=apps.callback.models.default_expiry)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('channel_id', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callback_requests', to='events.event')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callback_requests_made', to='extensions.extension')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callback_requests_received', to='extensions.extension')),
            ],
            options={
                'verbose_name': 'callback request',
                'verbose_name_plural': 'callback requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['state', 'next_attempt_at'], name='cb_req_state_next_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScheduledCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('repeat', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily')], default='once', max_length=5)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('retry_interval_minutes', models.PositiveSmallIntegerField(default=5)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('state', models.CharField(choices=[('scheduled', 'Scheduled'), ('dialing', 'Dialing'), ('answered', 'Answered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=10)),
                ('announcement', models.CharField(choices=[('default', 'Default wake-up announcement'), ('custom', 'Custom announcement')], default='default', max_length=8)),
                ('announcement_text', models.CharField(blank=True, help_text='Spoken via TTS.', max_length=300)),
                ('announcement_file', models.FileField(blank=True, null=True, upload_to=apps.callback.models.announcement_upload_to)),
                ('last_result', models.CharField(blank=True, max_length=200)),
                ('channel_id', models.CharField(blank=True, max_length=120)),
                ('snooze_minutes', models.PositiveSmallIntegerField(default=9)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_calls', to='events.event')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_calls', to='extensions.extension')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'scheduled call',
                'verbose_name_plural': 'scheduled calls',
                'ordering': ['scheduled_for'],
                'indexes': [models.Index(fields=['state', 'next_attempt_at'], name='cb_sched_state_next_idx')],
            },
        ),
        migrations.CreateModel(
            name='TestRingback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_number', models.CharField(max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('delay_seconds', models.PositiveSmallIntegerField(default=apps.callback.models.default_ringback_delay)),
                ('state', models.CharField(choices=[('scheduled', 'Scheduled'), ('dialing', 'Dialing'), ('delivered', 'Delivered'), ('failed', 'Failed')], db_index=True, default='scheduled', max_length=10)),
                ('channel_id', models.CharField(blank=True, max_length=120)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_ringbacks', to='events.event')),
                ('extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_ringbacks', to='extensions.extension')),
            ],
            options={
                'verbose_name': 'test ringback',
                'verbose_name_plural': 'test ringbacks',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['state', 'next_attempt_at'], name='cb_ringback_state_next_idx')],
            },
        ),
    ]
