# Generated by Django 5.2.17 on 2026-09-13 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dect', '0002_initial'),
        ('events', '0001_initial'),
        ('extensions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('src_number', models.CharField(blank=True, db_index=True, max_length=32)),
                ('dst_number', models.CharField(blank=True, db_index=True, max_length=32)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Seconds from dial to hangup.')),
                ('billsec', models.PositiveIntegerField(default=0, help_text='Seconds the call was connected.')),
                ('disposition', models.CharField(blank=True, db_index=True, max_length=20)),
                ('src_type', models.CharField(blank=True, max_length=20)),
                ('dst_type', models.CharField(blank=True, max_length=20)),
                ('uniqueid', models.CharField(max_length=150, unique=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dst_extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_calls', to='extensions.extension')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_records', to='events.event')),
                ('rfp', models.ForeignKey(blank=True, help_text='RFP serving the (DECT) caller, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_records', to='dect.rfp')),
                ('src_extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_calls', to='extensions.extension')),
            ],
            options={
                'verbose_name': 'call record',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtensionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('inbound', models.PositiveIntegerField(default=0)),
                ('outbound', models.PositiveIntegerField(default=0)),
                ('answered', models.PositiveIntegerField(default=0)),
                ('total_billsec', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_stats', to='events.event')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='extensions.extension')),
            ],
            options={
                'verbose_name': 'extension statistic',
                'ordering': ['-date'],
                'unique_together': {('event', 'extension', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HourlyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField(db_index=True)),
                ('calls', models.PositiveIntegerField(default=0)),
                ('answered', models.PositiveIntegerField(default=0)),
                ('total_billsec', models.PositiveIntegerField(default=0)),
                ('unique_callers', models.PositiveIntegerField(default=0)),
                ('by_type', models.JSONField(blank=True, default=dict)),
                ('by_disposition', models.JSONField(blank=True, default=dict)),
                ('by_rfp', models.JSONField(blank=True, default=dict)),
                ('caller_hashes', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_stats', to='events.event')),
            ],
            options={
                'verbose_name': 'hourly statistic',
                'ordering': ['hour'],
                'unique_together': {('event', 'hour')},
            },
        ),
    ]
