# Generated by Django 5.2.17 on 2026-09-13 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('extensions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, help_text='TTS text or an audio file path known to the PBX.')),
                ('audio', models.FileField(blank=True, null=True, upload_to='emergency/')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('targets', models.PositiveIntegerField(default=0)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_broadcasts', to='events.event')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_broadcasts', to='events.usergroup')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=8)),
                ('caller_number', models.CharField(blank=True, max_length=32)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('caller_extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_incidents', to='extensions.extension')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_incidents', to='events.event')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(help_text="Must be one of the plan's emergency numbers, e.g. 112.", max_length=8)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('fallback_number', models.CharField(blank=True, help_text='Dialed when the destination is missing/inactive (e.g. via PSTN).', max_length=32)),
                ('announce_location', models.BooleanField(default=True, help_text="Read the caller's location hint / RFP.")),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('destination_extension', models.ForeignKey(blank=True, help_text='Security / medics group or extension.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_targets', to='extensions.extension')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_targets', to='events.event')),
            ],
            options={
                'ordering': ['-priority', 'number'],
                'unique_together': {('event', 'number')},
            },
        ),
    ]
