# Generated by Django 5.2.17 on 2026-09-13 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('extensions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.CharField(choices=[('ringall', 'Ring all members at once'), ('roundrobin', 'Round robin (rotate who rings first)'), ('longestidle', 'Longest idle member first')], default='ringall', max_length=16)),
                ('ring_timeout', models.PositiveSmallIntegerField(default=20, help_text='Seconds to ring (per member for serial strategies).')),
                ('wrap_up_seconds', models.PositiveSmallIntegerField(default=0, help_text='Members are skipped for this many seconds after their last group call.')),
                ('allow_self_service', models.BooleanField(default=True, help_text='Members may log in/out themselves (portal and feature codes).')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callgroups', to='events.event')),
                ('extension', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='callgroup', to='extensions.extension')),
                ('user_group', models.ForeignKey(blank=True, help_text="Extensions of this user group's members join automatically.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callgroups', to='events.usergroup')),
            ],
            options={
                'verbose_name': 'call group',
                'ordering': ['extension__number'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logged_in', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Lower rings first (ties broken by strategy).')),
                ('last_call_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='extensions.extension')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='callgroups.callgroup')),
            ],
            options={
                'verbose_name': 'group member',
                'ordering': ['priority', 'extension__number'],
                'unique_together': {('group', 'extension')},
            },
        ),
        migrations.CreateModel(
            name='GroupLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('added', 'Added'), ('removed', 'Removed')], max_length=8)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('via', models.CharField(blank=True, help_text='web / api / feature-code / auto', max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_log', to='callgroups.groupmember')),
            ],
            options={
                'verbose_name': 'group login log',
                'ordering': ['-at'],
            },
        ),
    ]
