# Generated by Django 5.2.17 on 2026-09-14 03:00

import apps.callgroups.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callgroups', '0001_initial'),
        ('extensions', '0002_ringback_forwarding_toggles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='callgroup',
            name='admins',
            field=models.ManyToManyField(blank=True, help_text='Users who may manage members and settings besides the owner.', related_name='administered_callgroups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callgroup',
            name='shortcode',
            field=models.CharField(blank=True, help_text='Short label (e.g. SEC, MED) shown in front of the caller name when the group rings a member.', max_length=8),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='delay_s',
            field=models.PositiveSmallIntegerField(default=0, help_text='Ring-all only: seconds to wait before this member starts ringing.'),
        ),
        migrations.CreateModel(
            name='CallGroupInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('accepted', models.BooleanField(blank=True, help_text='Empty while open or when cancelled.', null=True)),
                ('token', models.CharField(default=apps.callgroups.models._new_token, editable=False, max_length=64, unique=True)),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callgroup_invites', to='extensions.extension')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='callgroups.callgroup')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'call group invite',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('responded_at__isnull', True)), fields=('group', 'extension'), name='callgroups_unique_open_invite')],
            },
        ),
    ]
