# Generated by Django 5.2.17 on 2026-09-13 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaccount',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Restrict the account to one event; empty = global.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_accounts', to='events.event'),
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
