# Generated by Django 5.2.17 on 2026-09-13 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('extensions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('sip_host', models.CharField(max_length=200)),
                ('port', models.PositiveIntegerField(default=5060)),
                ('transport', models.CharField(choices=[('udp', 'UDP'), ('tcp', 'TCP'), ('tls', 'TLS')], default='udp', max_length=3)),
                ('auth_user', models.CharField(blank=True, max_length=80)),
                ('auth_password', models.CharField(blank=True, max_length=128)),
                ('from_domain', models.CharField(blank=True, max_length=200)),
                ('outbound_prefix', models.CharField(default='0', help_text='Digits users dial first, e.g. 0.', max_length=8)),
                ('caller_id_default', models.CharField(blank=True, help_text='E.164 number presented by default.', max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakout_trunks', to='events.event')),
            ],
            options={
                'ordering': ['event', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OutboundRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('pattern', models.CharField(help_text='Regex matched against the number after the prefix.', max_length=120)),
                ('allow', models.BooleanField(default=True)),
                ('per_call_max_minutes', models.PositiveSmallIntegerField(default=0, help_text='0 = unlimited.')),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='Lower wins.')),
                ('trunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='breakout.trunk')),
            ],
            options={
                'ordering': ['priority', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='BreakoutPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed', models.BooleanField(default=True)),
                ('daily_minutes_limit', models.PositiveIntegerField(default=60, help_text='0 = unlimited.')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakout_permissions', to='events.event')),
                ('extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakout_permissions', to='extensions.extension')),
                ('user_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakout_permissions', to='events.usergroup')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('extension__isnull', False), ('user_group__isnull', False), _connector='OR'), name='breakout_permission_has_subject')],
            },
        ),
        migrations.CreateModel(
            name='BreakoutUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('minutes', models.FloatField(default=0)),
                ('calls', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakout_usage', to='events.event')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakout_usage', to='extensions.extension')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('extension', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CallerIdMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caller_id', models.CharField(max_length=32)),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakout_caller_ids', to='extensions.extension')),
                ('trunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caller_ids', to='breakout.trunk')),
            ],
            options={
                'unique_together': {('trunk', 'extension')},
            },
        ),
    ]
