# Generated by Django 5.2.17 on 2026-09-14 03:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('pbx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PBXJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('sync_extension', 'Sync extension'), ('remove_extension', 'Remove extension'), ('sync_device', 'Sync device'), ('remove_device', 'Remove device'), ('sync_event', 'Sync event'), ('set_mwi', 'Set MWI'), ('originate', 'Originate call'), ('broadcast', 'Broadcast'), ('hangup', 'Hangup'), ('custom', 'Custom')], max_length=20)),
                ('target_type', models.CharField(blank=True, help_text='extension / device / event', max_length=20)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Keyword arguments for the adapter call.')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('dead', 'Dead')], db_index=True, default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=120)),
                ('priority', models.SmallIntegerField(default=0, help_text='Higher runs first.')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pbx_jobs', to='events.event')),
            ],
            options={
                'verbose_name': 'PBX job',
                'ordering': ['-priority', 'next_attempt_at'],
            },
        ),
    ]
