# Generated by Django 5.2.17 on 2026-09-14 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_gsm'),
        ('pbx', '0002_pbxjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='PBXConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.CharField(default='asterisk', help_text='Adapter key from PET_PBX_BACKENDS.', max_length=40)),
                ('ari_url', models.URLField(blank=True, help_text='e.g. http://10.20.0.5:8088/ari', verbose_name='ARI URL')),
                ('ari_user', models.CharField(blank=True, max_length=64, verbose_name='ARI user')),
                ('ari_password', models.CharField(blank=True, max_length=128, verbose_name='ARI password')),
                ('ari_app', models.CharField(blank=True, default='pet', max_length=64, verbose_name='ARI application')),
                ('ami_host', models.CharField(blank=True, help_text='Empty = AMI disabled (ARI only).', max_length=200, verbose_name='AMI host')),
                ('ami_port', models.PositiveIntegerField(default=5038, verbose_name='AMI port')),
                ('ami_user', models.CharField(blank=True, max_length=64, verbose_name='AMI user')),
                ('ami_password', models.CharField(blank=True, max_length=128, verbose_name='AMI password')),
                ('hook_secret', models.CharField(blank=True, help_text='Sent by the venue Asterisk as X-PET-PBX-Secret on hooks, route lookups and phone provisioning. Empty = server-wide PET_PBX_HOOK_SECRET.', max_length=128, verbose_name='Hook secret')),
                ('notes', models.TextField(blank=True, help_text='Where the box is, who to call, VPN details...')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pbx_connection', to='events.event')),
            ],
            options={
                'verbose_name': 'PBX connection',
            },
        ),
    ]
