# Generated by Django 5.2.17 on 2026-09-14 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbx', '0003_pbxconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbxconnection',
            name='agent_asterisk_ok',
            field=models.BooleanField(blank=True, null=True, verbose_name='Agent reports Asterisk ok'),
        ),
        migrations.AddField(
            model_name='pbxconnection',
            name='agent_host',
            field=models.CharField(blank=True, max_length=200, verbose_name='Agent host'),
        ),
        migrations.AddField(
            model_name='pbxconnection',
            name='agent_last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Agent last seen'),
        ),
        migrations.AddField(
            model_name='pbxconnection',
            name='agent_message',
            field=models.CharField(blank=True, max_length=500, verbose_name='Agent message'),
        ),
        migrations.AddField(
            model_name='pbxconnection',
            name='agent_poll_interval',
            field=models.PositiveIntegerField(default=15, help_text='Seconds between snapshot polls of the venue agent.', validators=[django.core.validators.MinValueValidator(5)], verbose_name='Agent poll interval'),
        ),
        migrations.AddField(
            model_name='pbxconnection',
            name='agent_software',
            field=models.CharField(blank=True, max_length=64, verbose_name='Agent software'),
        ),
        migrations.AddField(
            model_name='pbxconnection',
            name='agent_version',
            field=models.CharField(blank=True, max_length=64, verbose_name='Applied snapshot version'),
        ),
        migrations.AddField(
            model_name='pbxconnection',
            name='provisioning',
            field=models.CharField(choices=[('shared_db', "Shared database – venue Asterisk reads PET's PostgreSQL"), ('agent', 'Venue agent – pulls snapshots over HTTPS into a local database')], default='shared_db', help_text='How the realtime rows reach the venue Asterisk.', max_length=12, verbose_name='Provisioning'),
        ),
    ]
