; DIAL - asterisk.conf
[directories](!)
astcachedir => /var/cache/asterisk
astetcdir => /etc/asterisk
astmoddir => /usr/lib/asterisk/modules
astvarlibdir => /var/lib/asterisk
astdbdir => /var/lib/asterisk
astkeydir => /var/lib/asterisk
astdatadir => /usr/share/asterisk
astagidir => /usr/share/asterisk/agi-bin
astspooldir => /var/spool/asterisk
astrundir => /var/run/asterisk
astlogdir => /var/log/asterisk
astsbindir => /usr/sbin

[options]
verbose = 3
debug = 0
; #exec in config files - used by extensions.conf to pull the [dial-<slug>] shell contexts from DIAL
execincludes = yes
hideconnect = yes
defaultlanguage = en
documentation_language = en_US
transmit_silence = yes
systemname = dial
live_dangerously = no
