; PET - logger.conf
[general]
dateformat=%F %T
appendhostname=no
queue_log=no
use_callids=yes

[logfiles]
console => notice,warning,error,verbose(3)
messages => notice,warning,error
security => security
; syslog.local0 => notice,warning,error
