# Generated by Django 5.2.17 on 2026-09-13 19:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dect', '0001_initial'),
        ('events', '0001_initial'),
        ('extensions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisioningProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('vendor', models.CharField(choices=[('snom', 'Snom'), ('yealink', 'Yealink'), ('grandstream', 'Grandstream'), ('cisco', 'Cisco'), ('generic', 'Generic')], max_length=20)),
                ('template', models.TextField(help_text='Django template; context: device, extension, event, sip_server, sip_port, transport.')),
                ('content_type', models.CharField(default='text/plain', max_length=60)),
                ('filename_pattern', models.CharField(default='{mac}.cfg', max_length=80)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_profiles', to='events.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('dect', 'DECT handset'), ('sip', 'SIP endpoint'), ('webrtc', 'WebRTC softphone'), ('gsm', 'GSM handset'), ('analog', 'Analog / ATA')], max_length=10)),
                ('name', models.CharField(blank=True, help_text="Free-form label, e.g. 'my orange handset'", max_length=80)),
                ('state', models.CharField(choices=[('new', 'New'), ('pending', 'Pending subscription'), ('subscribed', 'Subscribed / registered'), ('offline', 'Offline'), ('disabled', 'Disabled')], default='new', max_length=12)),
                ('ipei', models.CharField(blank=True, db_index=True, max_length=13, validators=[django.core.validators.RegexValidator('^\\d{13}$', 'IPEI must be 13 digits (5 digit EMC + 7 digit PSN + check).')])),
                ('subscription_pin', models.CharField(blank=True, max_length=16)),
                ('subscription_pin_expires_at', models.DateTimeField(blank=True, null=True)),
                ('omm_ppn', models.CharField(blank=True, help_text='Portable part number in the OMM.', max_length=32)),
                ('omm_user_id', models.CharField(blank=True, max_length=32)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('battery_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rssi', models.SmallIntegerField(blank=True, null=True)),
                ('handset_model', models.CharField(blank=True, max_length=60)),
                ('sip_username', models.CharField(blank=True, db_index=True, max_length=64)),
                ('sip_password', models.CharField(blank=True, max_length=128)),
                ('sip_password_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('sip_transport', models.CharField(choices=[('udp', 'UDP'), ('tcp', 'TCP'), ('tls', 'TLS'), ('wss', 'WSS')], default='udp', max_length=8)),
                ('sip_user_agent', models.CharField(blank=True, max_length=120)),
                ('sip_contact', models.CharField(blank=True, max_length=200)),
                ('sip_registered_at', models.DateTimeField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, db_index=True, max_length=17)),
                ('provisioning_token', models.CharField(blank=True, db_index=True, max_length=64)),
                ('imsi', models.CharField(blank=True, max_length=15)),
                ('msisdn', models.CharField(blank=True, max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='events.event')),
                ('last_seen_rfp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handsets', to='dect.rfp')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to=settings.AUTH_USER_MODEL)),
                ('provisioning_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='devices.provisioningprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Serial ring order; lower first.')),
                ('ring_delay', models.PositiveSmallIntegerField(default=0, help_text='Seconds to wait before ringing.')),
                ('is_active', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='devices.device')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='extensions.extension')),
            ],
            options={
                'ordering': ['priority'],
                'unique_together': {('extension', 'device')},
            },
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('ipei', ''), _negated=True), fields=('event', 'ipei'), name='unique_ipei_per_event'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('sip_username', ''), _negated=True), fields=('sip_username',), name='unique_sip_username'),
        ),
    ]
