# Generated by Django 5.2.17 on 2026-09-14 03:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DECTManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emc', models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'The EMC is the first 5 digits of an IPEI.')], verbose_name='EMC')),
                ('name', models.CharField(max_length=80)),
                ('models_hint', models.TextField(blank=True, help_text="Known handset models with this EMC, e.g. '612d, 622d'.")),
                ('source', models.CharField(choices=[('builtin', 'Built-in'), ('user', 'User contributed')], default='user', max_length=10)),
            ],
            options={
                'verbose_name': 'DECT manufacturer',
                'ordering': ['emc'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='gsm_2g',
            field=models.BooleanField(default=True, help_text='SIM may attach to GSM/GPRS.', verbose_name='2G'),
        ),
        migrations.AddField(
            model_name='device',
            name='gsm_3g',
            field=models.BooleanField(default=False, help_text='SIM may attach to UMTS.', verbose_name='3G'),
        ),
        migrations.AddField(
            model_name='device',
            name='gsm_4g',
            field=models.BooleanField(default=False, help_text='SIM may attach to LTE.', verbose_name='4G'),
        ),
        migrations.AddField(
            model_name='device',
            name='gsm_5g',
            field=models.BooleanField(default=False, help_text='SIM may attach to NR.', verbose_name='5G'),
        ),
        migrations.AddField(
            model_name='device',
            name='gsm_register_token',
            field=models.CharField(blank=True, db_index=True, help_text='One-time code the user dials/texts on the GSM network to link the SIM to this device.', max_length=32),
        ),
        migrations.AddField(
            model_name='device',
            name='gsm_registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='uak',
            field=models.CharField(blank=True, help_text='User Authentication Key stored by the OMM; lets a handset re-subscribe without a new PIN.', max_length=64),
        ),
    ]
