# Generated by Django 5.2.17 on 2026-09-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_dect_manufacturer_gsm_uak'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='unclaimed',
            field=models.BooleanField(db_index=True, default=False, help_text='Pool handset: subscribed to the DECT network but not yet bound to an extension. Its user dials the claim code of an extension to take it over.'),
        ),
    ]
