# Generated by Django 5.2.17 on 2026-09-13 22:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extensions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('pin', models.CharField(blank=True, help_text='4-8 digits; leave blank for an open room.', max_length=8, validators=[django.core.validators.RegexValidator('^\\d{4,8}$')])),
                ('max_participants', models.PositiveSmallIntegerField(default=20)),
                ('record', models.BooleanField(default=False)),
                ('music_on_hold', models.BooleanField(default=True, help_text='Play MoH while alone in the room.')),
                ('announce_join', models.BooleanField(default=True, help_text='Play a tone when someone joins/leaves.')),
                ('is_public', models.BooleanField(default=True, verbose_name='Listed for everyone')),
                ('extension', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conference_room', to='extensions.extension')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conference_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['extension__number'],
            },
        ),
        migrations.CreateModel(
            name='ConferenceParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_id', models.CharField(db_index=True, max_length=120)),
                ('caller_number', models.CharField(blank=True, max_length=32)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='conferences.conferenceroom')),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
    ]
