# Generated by Django 5.2.17 on 2026-09-13 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FederationDirectoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance_url', models.URLField()),
                ('event_name', models.CharField(max_length=120)),
                ('event_slug', models.SlugField(blank=True)),
                ('dial_prefix', models.CharField(blank=True, max_length=8)),
                ('sip_host', models.CharField(blank=True, max_length=200)),
                ('sip_port', models.PositiveIntegerField(default=5061)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['event_name'],
                'unique_together': {('instance_url', 'event_slug')},
            },
        ),
        migrations.CreateModel(
            name='FederationPeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('remote_prefix', models.CharField(help_text='Digits users dial first to reach this peer.', max_length=8)),
                ('sip_host', models.CharField(max_length=200)),
                ('sip_port', models.PositiveIntegerField(default=5061)),
                ('transport', models.CharField(choices=[('tls', 'TLS'), ('tcp', 'TCP'), ('udp', 'UDP'), ('wss', 'WSS')], default='tls', max_length=4)),
                ('srtp', models.BooleanField(default=True)),
                ('auth_user', models.CharField(blank=True, max_length=80)),
                ('auth_password', models.CharField(blank=True, max_length=128)),
                ('remote_event_name', models.CharField(blank=True, max_length=120)),
                ('directory_url', models.URLField(blank=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('disabled', 'Disabled')], db_index=True, default='pending', max_length=10)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='federation_peers', to='events.event')),
            ],
            options={
                'ordering': ['remote_prefix'],
                'unique_together': {('event', 'remote_prefix')},
            },
        ),
    ]
