# Generated by Django 5.2.17 on 2026-09-13 19:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_length', models.PositiveSmallIntegerField(default=3)),
                ('max_length', models.PositiveSmallIntegerField(default=5)),
                ('default_requires_approval', models.BooleanField(default=False, help_text='If no range matches: require approval instead of instant activation.')),
                ('default_allowed', models.BooleanField(default=True, help_text='If no range matches: allow registration at all.')),
                ('test_ringback_number', models.CharField(blank=True, default='', max_length=16, validators=[django.core.validators.RegexValidator('^\\d*$', 'Digits only')])),
                ('wakeup_service_number', models.CharField(blank=True, default='', max_length=16, validators=[django.core.validators.RegexValidator('^\\d*$', 'Digits only')])),
                ('site_survey_number', models.CharField(blank=True, default='', max_length=16, validators=[django.core.validators.RegexValidator('^\\d*$', 'Digits only')])),
                ('echo_test_number', models.CharField(blank=True, default='', max_length=16, validators=[django.core.validators.RegexValidator('^\\d*$', 'Digits only')])),
                ('voicemail_number', models.CharField(blank=True, default='', max_length=16, validators=[django.core.validators.RegexValidator('^\\d*$', 'Digits only')])),
                ('emergency_numbers', models.JSONField(blank=True, default=list, help_text='Numbers that are always blocked from registration and routed to on-site emergency.')),
                ('callback_request_code', models.CharField(default='*66', max_length=8)),
                ('callback_cancel_code', models.CharField(default='*86', max_length=8)),
                ('group_login_code', models.CharField(default='*71', max_length=8)),
                ('group_logout_code', models.CharField(default='*72', max_length=8)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='number_plan', to='events.event')),
            ],
            options={
                'verbose_name': 'number plan',
            },
        ),
        migrations.CreateModel(
            name='NumberRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('priority', models.IntegerField(default=100, help_text='Lower matches first.')),
                ('is_active', models.BooleanField(default=True)),
                ('prefix', models.CharField(blank=True, help_text='Match numbers starting with this prefix.', max_length=16, validators=[django.core.validators.RegexValidator('^\\d*$', 'Digits only')])),
                ('pattern', models.CharField(blank=True, help_text='Optional regex (anchored) instead of/in addition to prefix.', max_length=120)),
                ('min_length', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_length', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('open', 'Open - instant self-service'), ('approval', 'Requires approval'), ('restricted', 'Restricted to roles/groups'), ('blocked', 'Blocked')], default='open', max_length=20)),
                ('allowed_roles', models.JSONField(blank=True, default=list, help_text="Roles allowed in RESTRICTED mode, e.g. ['orga','helpdesk'].")),
                ('allowed_types', models.JSONField(blank=True, default=list, help_text='Extension types allowed here; empty = all.')),
                ('is_vanity', models.BooleanField(default=False, help_text='Premium/vanity - always needs approval.')),
                ('quota_per_user', models.PositiveIntegerField(blank=True, null=True)),
                ('allowed_groups', models.ManyToManyField(blank=True, related_name='allowed_ranges', to='events.usergroup')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='numbering.numberplan')),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
    ]
