# Generated by Django 5.2.17 on 2026-09-14 03:03

import apps.numbering.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('extensions', '0002_ringback_forwarding_toggles'),
        ('numbering', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='numberplan',
            name='prefix_free',
            field=models.BooleanField(default=True, help_text='Variable-length numbers: no extension may be a prefix of another one (23 blocks 2323 and vice versa), so every number is dialable without a timeout.', verbose_name='Prefix-free numbering'),
        ),
        migrations.CreateModel(
            name='ExtensionClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(db_index=True, max_length=16, validators=[django.core.validators.RegexValidator('^\\d*$', 'Digits only')])),
                ('type', models.CharField(choices=[('dect', 'DECT handset'), ('sip', 'SIP endpoint'), ('gsm', 'GSM (local cell network)'), ('webrtc', 'WebRTC browser softphone'), ('analog', 'Analog via ATA'), ('group', 'Call group / hunt group'), ('announcement', 'Announcement'), ('ivr', 'IVR menu'), ('conference', 'Conference room'), ('voicemail', 'Voicemail box'), ('app', 'Application / service'), ('federation', 'Federation trunk (DIAL-VPN)'), ('breakout', 'PSTN breakout')], default='dect', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Invite address if the person has no account yet.', max_length=254)),
                ('token', models.CharField(default=apps.numbering.models._new_token, max_length=64, unique=True)),
                ('valid_until', models.DateTimeField(default=apps.numbering.models._default_claim_validity)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_claims', to='events.event')),
                ('redeemed_extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='extensions.extension')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extension_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'extension claim',
                'ordering': ['number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExtensionPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('prefix', models.CharField(blank=True, help_text='All numbers in the pool start with these digits.', max_length=16, validators=[django.core.validators.RegexValidator('^\\d*$', 'Digits only')])),
                ('length', models.PositiveSmallIntegerField(default=4, help_text='Total number of digits.')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_pools', to='events.event')),
            ],
            options={
                'verbose_name': 'extension pool',
                'ordering': ['prefix', 'length', 'id'],
            },
        ),
    ]
