# Generated by Django 5.2.17 on 2026-09-14 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbering', '0002_prefix_free_pools_claims'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberplan',
            name='dect_claim_number',
            field=models.CharField(blank=True, default='', help_text='Users dial this number followed by the claim code shown on their extension page to bind the handset they are calling from to that extension (GURU3-style). Empty = feature off.', max_length=16, validators=[django.core.validators.RegexValidator('^\\d*$', 'Digits only')], verbose_name='DECT claim number'),
        ),
    ]
