# Generated by Django 5.2.17 on 2026-09-14 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbering', '0003_dect_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberplan',
            name='announcement_record_number',
            field=models.CharField(blank=True, default='', help_text='Owners dial this number followed by the recording code shown on their announcement page (or enter it after the prompt) to record the announcement with their phone. Empty = feature off.', max_length=16, validators=[django.core.validators.RegexValidator('^\\d*$', 'Digits only')], verbose_name='Announcement recording number'),
        ),
        migrations.AddField(
            model_name='numberplan',
            name='forward_busy_code',
            field=models.CharField(blank=True, default='*22', help_text='Dial <code><number> to forward calls to <number> only while you are busy.', max_length=8, verbose_name='Forward when busy'),
        ),
        migrations.AddField(
            model_name='numberplan',
            name='forward_clear_code',
            field=models.CharField(blank=True, default='*20', help_text='Dial this code on its own to switch every forwarding of your extension off.', max_length=8, verbose_name='Forward off (clear)'),
        ),
        migrations.AddField(
            model_name='numberplan',
            name='forward_noanswer_code',
            field=models.CharField(blank=True, default='*23', help_text='Dial <code><number> to forward calls to <number> when you do not pick up.', max_length=8, verbose_name='Forward on no answer'),
        ),
        migrations.AddField(
            model_name='numberplan',
            name='forward_set_code',
            field=models.CharField(blank=True, default='*21', help_text='Dial <code><number> to forward all calls to <number>, e.g. *214242. Empty = off.', max_length=8, verbose_name='Forward always (set)'),
        ),
    ]
