# Generated by Django 5.2.17 on 2026-09-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbering', '0004_forward_codes_record_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionclaim',
            name='type',
            field=models.CharField(choices=[('dect', 'DECT handset'), ('sip', 'SIP endpoint'), ('gsm', 'GSM (local cell network)'), ('webrtc', 'WebRTC browser softphone'), ('analog', 'Analog via ATA'), ('group', 'Call group / hunt group'), ('announcement', 'Announcement'), ('ivr', 'IVR menu'), ('conference', 'Conference room'), ('voicemail', 'Voicemail box'), ('app', 'Application / service'), ('federation', 'Federation trunk (PET-VPN)'), ('breakout', 'PSTN breakout'), ('trunk', 'SIP trunk (number block)')], default='dect', max_length=20),
        ),
    ]
