# Generated by Django 5.2.17 on 2026-09-13 21:51

import apps.voicemail.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('extensions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pin', models.CharField(help_text='4-6 digits, entered on the handset to listen to messages.', max_length=6)),
                ('email_delivery', models.BooleanField(default=False, verbose_name='Send new messages by e-mail')),
                ('email', models.EmailField(blank=True, help_text='Overrides the account e-mail address.', max_length=254)),
                ('greeting', models.FileField(blank=True, null=True, upload_to=apps.voicemail.models._greeting_path)),
                ('max_messages', models.PositiveSmallIntegerField(default=50)),
                ('enabled', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailboxes', to='events.event')),
                ('extension', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox', to='extensions.extension')),
            ],
            options={
                'verbose_name': 'mailbox',
                'verbose_name_plural': 'mailboxes',
                'ordering': ['extension__number'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caller_number', models.CharField(blank=True, max_length=32)),
                ('caller_name', models.CharField(blank=True, max_length=80)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('audio', models.FileField(blank=True, null=True, upload_to=apps.voicemail.models._message_path)),
                ('is_read', models.BooleanField(default=False)),
                ('transcript', models.TextField(blank=True)),
                ('asterisk_msg_id', models.CharField(blank=True, db_index=True, help_text='Original spool path / msg id, used for de-duplication.', max_length=255)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='voicemail.mailbox')),
            ],
            options={
                'verbose_name': 'voicemail message',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='email', max_length=10)),
                ('recipient', models.CharField(blank=True, max_length=200)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('ok', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='voicemail.message')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
