# Generated by Django 5.2.17 on 2026-09-14 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_event_gsm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text="Used in the page address, e.g. 'how-to-dect'.")),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(blank=True, help_text='Markdown. Raw HTML is shown as text, not rendered.')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers come first.')),
                ('published', models.BooleanField(default=True, help_text='Unpublished pages are only visible to the orga.')),
                ('show_on_dashboard', models.BooleanField(default=False, help_text='Also list this page on the event dashboard.')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='events.event')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Info page',
                'verbose_name_plural': 'Info pages',
                'ordering': ['order', 'title'],
                'unique_together': {('event', 'slug')},
            },
        ),
    ]
