# Generated by Django 5.2.17 on 2026-09-13 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhonebookSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intro_text', models.TextField(blank=True, help_text='Shown above the phonebook (also on the PDF).')),
                ('show_location', models.BooleanField(default=True, verbose_name='Show location hints')),
                ('show_owner', models.BooleanField(default=True, verbose_name='Show owner nicknames')),
                ('categories', models.JSONField(blank=True, default=list, help_text='List of {name, prefix} objects used to group entries.')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phonebook_settings', to='events.event')),
            ],
            options={
                'verbose_name': 'phonebook settings',
                'verbose_name_plural': 'phonebook settings',
            },
        ),
    ]
