# Generated by Django 5.2.17 on 2026-09-14 19:50

import apps.phonebook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonebooksettings',
            name='directory_enabled',
            field=models.BooleanField(default=True, help_text='Serve the phonebook to desk phones, the DECT OMM and LDAP clients.', verbose_name='Remote directory enabled'),
        ),
        migrations.AddField(
            model_name='phonebooksettings',
            name='directory_token',
            field=models.CharField(default=apps.phonebook.models._directory_token, help_text='Secret in remote-phonebook URLs and the LDAP bind password. Rotate it to lock out every phone at once.', max_length=64, verbose_name='Directory token'),
        ),
    ]
