# Generated by Django 5.2.17 on 2026-09-13 22:09

import apps.ivr.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('extensions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to=apps.ivr.models._audio_path)),
                ('tts_text', models.TextField(blank=True, help_text='Spoken when no audio file is uploaded.')),
                ('language', models.CharField(default='en', max_length=8)),
                ('loop', models.BooleanField(default=False, help_text='Repeat until the caller hangs up.')),
                ('extension', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='announcement', to='extensions.extension')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FunService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('echo', 'Echo test'), ('time', 'Speaking clock'), ('moh', 'Music on hold'), ('song', 'Dial-a-song')], max_length=10)),
                ('audio', models.FileField(blank=True, help_text='Dial-a-song audio.', null=True, upload_to='ivr/songs/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fun_services', to='events.event')),
                ('extension', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fun_service', to='extensions.extension')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IVRMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt_audio', models.FileField(blank=True, null=True, upload_to=apps.ivr.models._audio_path)),
                ('prompt_tts', models.TextField(blank=True)),
                ('language', models.CharField(default='en', max_length=8)),
                ('timeout', models.PositiveSmallIntegerField(default=5, help_text='Seconds to wait for a digit.')),
                ('invalid_retries', models.PositiveSmallIntegerField(default=3)),
                ('options', models.JSONField(blank=True, default=list)),
                ('extension', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ivr_menu', to='extensions.extension')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
