# Generated by Django 5.2.17 on 2026-09-13 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSurveyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rssi', models.SmallIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='SyncCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster_id', models.CharField(max_length=16)),
                ('name', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='VenueMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('image', models.ImageField(upload_to='venue_maps/')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('omm_id', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=80)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('sync_source', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('connected', models.BooleanField(default=False)),
                ('synced', models.BooleanField(default=False)),
                ('last_state_change', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('active_calls', models.PositiveSmallIntegerField(default=0)),
                ('pos_x', models.FloatField(blank=True, null=True)),
                ('pos_y', models.FloatField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfps', to='events.event')),
            ],
            options={
                'verbose_name': 'RFP',
                'verbose_name_plural': 'RFPs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=10)),
                ('kind', models.CharField(db_index=True, max_length=40)),
                ('message', models.CharField(max_length=300)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notified', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='events.event')),
                ('rfp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='dect.rfp')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RFPStatusSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(db_index=True)),
                ('connected', models.BooleanField()),
                ('synced', models.BooleanField()),
                ('active_calls', models.PositiveSmallIntegerField(default=0)),
                ('handsets', models.PositiveSmallIntegerField(default=0)),
                ('rfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='dect.rfp')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
