# Generated by Django 5.2.17 on 2026-09-13 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dect', '0001_initial'),
        ('devices', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesurveylog',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.device'),
        ),
        migrations.AddField(
            model_name='sitesurveylog',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_logs', to='events.event'),
        ),
        migrations.AddField(
            model_name='sitesurveylog',
            name='rfp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dect.rfp'),
        ),
        migrations.AddField(
            model_name='synccluster',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_clusters', to='events.event'),
        ),
        migrations.AddField(
            model_name='rfp',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfps', to='dect.synccluster'),
        ),
        migrations.AddField(
            model_name='venuemap',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_maps', to='events.event'),
        ),
        migrations.AddField(
            model_name='rfp',
            name='venue_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfps', to='dect.venuemap'),
        ),
        migrations.AlterUniqueTogether(
            name='synccluster',
            unique_together={('event', 'cluster_id')},
        ),
        migrations.AlterUniqueTogether(
            name='rfp',
            unique_together={('event', 'omm_id')},
        ),
    ]
