# Generated by Django 5.2.17 on 2026-09-14 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dect', '0002_initial'),
        ('events', '0002_event_gsm'),
    ]

    operations = [
        migrations.CreateModel(
            name='DECTConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backend', models.CharField(default='omm', help_text='Adapter key from DIAL_DECT_BACKENDS.', max_length=40)),
                ('host', models.CharField(blank=True, help_text='IP or hostname of the OMM.', max_length=200, verbose_name='OMM host')),
                ('port', models.PositiveIntegerField(default=12622, verbose_name='AXI port')),
                ('user', models.CharField(blank=True, default='omm', max_length=64, verbose_name='AXI user')),
                ('password', models.CharField(blank=True, max_length=128, verbose_name='AXI password')),
                ('verify_tls', models.BooleanField(default=False, verbose_name='Verify TLS certificate')),
                ('notes', models.TextField(blank=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dect_connection', to='events.event')),
            ],
            options={
                'verbose_name': 'DECT connection',
            },
        ),
    ]
